spring:
  application:
    name: API
server:
  port: ${PORT:${SERVER_PORT:0}}
security:
  oauth2:
    client:
      client-id: client
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      id: api  #指定资源的唯一标识。
      user-info-uri: http://localhost:8080/user #指定获取用户信息的地址，即之前在授权中心返回了Principal 的Controller
      prefer-token-info: false #是否检查token 信息，设置为副se 时，贝lj 指定使用用户信息进行验证。
eureka:
  client:
    service-url: http://localhost:8082/eureka/
